#Need proper header
#TARGET_BOARD_PLATFORM is defined in BoardConfig.mk which will be included later
TARGET_BOARD_PLATFORM := java

PRODUCT_PACKAGES += \
	charger \
	charger_res_images \
	usb_portd \
	usbdev_mode \
	libGLES_java \
	atx \
	atxd \
	bkmgrd \
	runSysCmd \
	watchdogd \
	libasound \
	libat \
	libatlog \
	libbrcm_ril \
	libbrcmaacenc \
	libbrcmamrnbaridec \
	libbrcmamrnbarienc \
	libbrcmamrwbaridec \
	libbrcmamrwbarienc \
	libbrcmheaacdecoder \
	libbrcmmp3dec \
	libbrcmmp3enc \
	libBrcmOMX_Component \
	libBrcmOMX_Core \
	libOMX.brcm.audio.aac.decoder \
	libOMX.brcm.audio.aac.encoder \
	libOMX.brcm.audio.amrnb.decoder \
	libOMX.brcm.audio.amrnb.encoder \
	libOMX.brcm.audio.amrwb.decoder \
	libOMX.brcm.audio.amrwb.encoder \
	libOMX.brcm.audio.dummy.decoder \
	libOMX.brcm.audio.mp3.decoder \
	libOMX.brcm.audio.mp3.encoder \
	libOMX.brcm.video.dummy.decoder \
	libOMX.brcm.video.dummy.encoder \
	libOMX.brcm.video.h263.decoder \
	libOMX.brcm.video.h263.encoder \
	libOMX.brcm.video.h264.decoder \
	libOMX.brcm.video.h264.encoder \
	libOMX.brcm.video.mpeg4.decoder \
	libOMX.brcm.video.mpeg4.encoder \
	libOMX.brcm.audio.wma.decoder \
	libOMX.brcm.video.h264.hw.decoder \
	libOMX.brcm.video.h264.hw.encoder \
	libOMX.brcm.video.mpeg4.hw.decoder \
	libOMX.brcm.video.vc1.hw.decoder \
	libhwcodec \
	libhwcodec_memutils \
	libcontainers \
	libisp3 \
	libv3d2 \
	libbrcmwmadec \
	libmp3_dec_dummy \
	libmp3_enc_dummy \
	libmpeg4_dummy_enc \
	libmpeg4_fake_dec \
	libV3D_driver \
	libV3D_server \
	libv4l2 \
	libVCE_csl \
	libVCE_driver \
	libVCE_imageconv \
	libVCE_vtq \
	libwmv_dec_mp \
	libwmv_dec_sp \
	libh263_dummy_enc \
	libh264_enc_bp \
	libh264_dummy_enc \
	libh264_enc_bp \
	libstagefrighthw \
	audio.primary.$(TARGET_BOARD_PLATFORM) \
	acoustics.default \
	alsa.default \
	audio.a2dp.default \
	audio.r_submix.default \
	audio_policy.$(TARGET_BOARD_PLATFORM) \
	gralloc.$(TARGET_BOARD_PLATFORM) \
	camera.$(TARGET_BOARD_PLATFORM) \
	gps.$(TARGET_BOARD_PLATFORM) \
	glgps \
	hwcomposer.$(TARGET_BOARD_PLATFORM) \
	libbralloc \
	libbrcm_ril \
	libCamDrv \
	libcapi2 \
	libcate_rpc \
	libcli \
	libcolor_space \
	libISP \
	libisp2 \
	libpagemap \
	libps_dunmgr \
	librpc \
	libUnicam \
	liburilclient \
	libusb \
	cate_rpc_util \
	libppphook \
	libvt_codec \
	libvtqinit \
	libcodec_util \
	libh263_dec_p3 \
	libh263_enc_p3 \
	libh264_dec_bp \
	libh264_enc_bp \
	libmpeg4_dec_asp \
	libmpeg4_enc_sp \
	libvpx_dec \
	libOMX.brcm.video.vpx.decoder \
	libh264_dec_hp \
	libqpudeblock \
	libv3d \
	libvcetestcmn \
	libaudiotest \
	lights.goldfish \
	sensors.goldfish \
	invoke_mock_media_player \
	libaac_enc_dummy \
	libasound_module_pcm_bcmfilter \
	camera.goldfish \
	bcmtest_copy \
	gps.goldfish \
	libat_prebuilt \
	libcom_google_ase_Exec \
	libxml \
	btld \
	BCM2076B1_002.002.004.0034.0000.hcd \
	BCM4334B0_v142_TestOnly_26MHz_wlbga_extLna_Pd.hcd \
	BCM4334B0_V56_TestOnly_26MHz_wlbga_extLna.hcd \
	BCM4334B0_002.001.013.0056.0066.B53.FM.I2S.Slave.v1.TESTONLY.hcd \
	BCM4334B0_002.001.013.0079.0088.hcd \
	BCM4334B0_002.001.013.0142.0145_RC.hcd \
	BCM2076B1_002.002.004.0032.0000.hcd \
	BCM4330B1_002.001.003.0550.0000.hcd \
	BCM4334B0_002.001.013.0178.0221_RC.hcd \
	BCM4330B1_002.001.003.0750.0878.hcd \
	BCM4330B1_002.001.003.0967.0000_Samsung_Java-TEST-ONLY.hcd \
	glconfig2076.xml \
	glconfig47511.xml \
	glconfig47511_ss.xml \
	libbt-client-api \
	com.broadcom.bt \
	com.broadcom.bt.xml \
	FmRadio \
	libfmservice \
	make_ext4fs \
	com.google.widevine.software.drm.xml \
	com.google.widevine.software.drm \
	libdrmwvmplugin \
	libwvm \
	libWVStreamControlAPI_L3 \
	libwvdrm_L3 \
	libdrmdecrypt \
	dhcpcd.conf \
	SmartcardService \
	org.simalliance.openmobileapi \
	org.simalliance.openmobileapi.xml \
	libassd \
	libispraw \
	libjpeg_turbo \
	libqpuprocess \
	libtiming \
	libOMX.brcm.video.h264.async.hw.encoder \
	libdrmdecrypt \
	libFraunhoferAAC \
	atx_rndis.conf \
	netconsole.sh \
	udhcpd.conf \
	udhcpd_ncm.conf \
	usb_network.sh \
	usb_portd.conf \
	usb_save.sh \
	usb_tether.sh \
	usbdev.sh


# In Java TK platform, build them in all mode(user/eng/debug... etc).
PRODUCT_PACKAGES += \
	gpslogd \
	glconfig.xml \
	gps.conf \
	gps.java.so \
	bt_vendor.conf \
	libbt-codec_aptx.so